### ISSUE TITLE
iphone - clicking "Add to Calendar" nothing happen

### ISSUE THREAD

**Issue by yong-asial** [juan-serrano-soria/workout-app#22]
i tested on my Iphone and when clicking on "Add to Calendar", nothing happened.

if i connect to safari developer tool, i could see following errors

```
[Log] native CapacitorCalendar.saveEventToCalendar (#52387636) (user-script:2, line 335)
[Log] Object (user-script:2, line 342)

callbackId: "52387636"

methodName: "saveEventToCalendar"

options: {eventTitle: "Workout day 1", eventDescription: "Do this today: undefined, undefined, undefined, undefined", location: "Gym"}

pluginId: "CapacitorCalendar"

type: "message"

Object Prototype

[Log] result CapacitorCalendar.saveEventToCalendar (#52387636) (user-script:2, line 309)
[Error] {errorMessage: "", message: ""}
	(anonymous function) (user-script:2:317)
	returnResult (user-script:2:895)
	(anonymous function) (user-script:2:890)
	Global Code (Script Element 1:1)
[Error] Unhandled Promise Rejection: Error
```

**Comment by yong-asial** [comment]
on Android, it is working fine.

**Comment by yong-asial** [comment]
it is working after adding permission ( - NSCalendarsUsageDescription: 'Access Calendar')  to config.yaml

```
platforms:
  android:
    versionName: 1.0.0
    manifest:
      -
        file: AndroidManifest.xml
        target: manifest/application/activity
        attrs:
          'android:screenOrientation': unspecified
  ios:
    targets:
      App:
        version: 1.0.0
        xcconfig:
          -
            file: App/Config.xcconfig
            set:
              TARGETED_DEVICE_FAMILY: '1,2'
        plist:
          -
            replace: true
            entries:
              -
                UISupportedInterfaceOrientations:
                  - UIInterfaceOrientationPortrait
                  - UIInterfaceOrientationLandscapeLeft
                  - UIInterfaceOrientationLandscapeRight
              - NSCalendarsUsageDescription: 'Access Calendar'

```
